"""
AutobahnWarningTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .autobahn_warning_collection import AutobahnWarningCollection
from .response import Response
from .response_exception import ResponseException

class AutobahnWarningTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)


    def get_all(self, autobahn_id: str) -> AutobahnWarningCollection:
        """
        Returns available warnings for a specific autobahn
        """
        try:
            path_params = {}
            path_params['autobahn_id'] = autobahn_id

            query_params = {}

            query_struct_names = []

            url = self.parser.url('/autobahn/:autobahn_id/warning', path_params)

            options = {}
            options['headers'] = {}
            options['params'] = self.parser.query(query_params, query_struct_names)



            response = self.http_client.request('GET', url, **options)

            if response.status_code >= 200 and response.status_code < 300:
                data = AutobahnWarningCollection.model_validate_json(json_data=response.content)

                return data

            statusCode = response.status_code
            if statusCode == 400:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 404:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 500:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            raise sdkgen.UnknownStatusCodeException('The server returned an unknown status code: ' + str(statusCode))
        except RequestException as e:
            raise sdkgen.ClientException('An unknown error occurred: ' + str(e))



