"""
BudgetTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .budget_expense_tag import BudgetExpenseTag
from .budget_income_tag import BudgetIncomeTag

class BudgetTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)

    def expense(self) -> BudgetExpenseTag:
        return BudgetExpenseTag(
            self.http_client,
            self.parser
        )

    def income(self) -> BudgetIncomeTag:
        return BudgetIncomeTag(
            self.http_client,
            self.parser
        )


