"""
budget automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal


class Budget(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    label: Optional[str] = Field(default=None, alias="label")
    value: Optional[int] = Field(default=None, alias="value")
    relative_to_parent_value: Optional[int] = Field(default=None, alias="relativeToParentValue")
    relative_value: Optional[int] = Field(default=None, alias="relativeValue")


