"""
BundesratTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .bundesrat_member_tag import BundesratMemberTag

class BundesratTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)

    def member(self) -> BundesratMemberTag:
        return BundesratMemberTag(
            self.http_client,
            self.parser
        )


