"""
DistrictTag automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .district import District
from .district_collection import DistrictCollection
from .response import Response
from .response_exception import ResponseException

class DistrictTag(sdkgen.TagAbstract):
    def __init__(self, http_client: requests.Session, parser: sdkgen.Parser):
        super().__init__(http_client, parser)


    def get(self, district_id: str) -> District:
        """
        Returns a specific district
        """
        try:
            path_params = {}
            path_params['district_id'] = district_id

            query_params = {}

            query_struct_names = []

            url = self.parser.url('/district/:district_id', path_params)

            options = {}
            options['headers'] = {}
            options['params'] = self.parser.query(query_params, query_struct_names)



            response = self.http_client.request('GET', url, **options)

            if response.status_code >= 200 and response.status_code < 300:
                data = District.model_validate_json(json_data=response.content)

                return data

            statusCode = response.status_code
            if statusCode == 400:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 404:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 500:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            raise sdkgen.UnknownStatusCodeException('The server returned an unknown status code: ' + str(statusCode))
        except RequestException as e:
            raise sdkgen.ClientException('An unknown error occurred: ' + str(e))

    def get_all(self, start_index: int, state: str, name: str) -> DistrictCollection:
        """
        Returns all available districts
        """
        try:
            path_params = {}

            query_params = {}
            query_params['startIndex'] = start_index
            query_params['state'] = state
            query_params['name'] = name

            query_struct_names = []

            url = self.parser.url('/district', path_params)

            options = {}
            options['headers'] = {}
            options['params'] = self.parser.query(query_params, query_struct_names)



            response = self.http_client.request('GET', url, **options)

            if response.status_code >= 200 and response.status_code < 300:
                data = DistrictCollection.model_validate_json(json_data=response.content)

                return data

            statusCode = response.status_code
            if statusCode == 400:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 404:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            if statusCode == 500:
                data = Response.model_validate_json(json_data=response.content)

                raise ResponseException(data)

            raise sdkgen.UnknownStatusCodeException('The server returned an unknown status code: ' + str(statusCode))
        except RequestException as e:
            raise sdkgen.ClientException('An unknown error occurred: ' + str(e))



