"""
job_location automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
from .job_coordinate import JobCoordinate


class JobLocation(BaseModel):
    zip: Optional[str] = Field(default=None, alias="zip")
    place: Optional[str] = Field(default=None, alias="place")
    state: Optional[str] = Field(default=None, alias="state")
    country: Optional[str] = Field(default=None, alias="country")
    coordinate: Optional[JobCoordinate] = Field(default=None, alias="coordinate")


