"""
news automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union, Literal
import datetime


class News(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    title: Optional[str] = Field(default=None, alias="title")
    link: Optional[str] = Field(default=None, alias="link")
    updated: Optional[datetime.datetime] = Field(default=None, alias="updated")


