"""
ResponseException automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import sdkgen
from typing import Dict
from typing import Any

from .response import Response

class ResponseException(sdkgen.KnownStatusCodeException):
    payload: Response = None

    def __init__(self, payload):
        self.payload = payload

    def get_payload(self) -> Response:
        return self.payload
